config/routes.rb
Ideclarevar::Application.routes.draw do  
  
  get "public/index"  
  get "public/search"
  get 'public/view/:id', to: 'public#view', as: 'view'
  get 'public/yadg'  
  get 'public/weather'
  get 'public/search_tag_get'
  devise_for :users
  namespace :admin, :path => 'admin' do
    get '/add' => "admin#add"
    post '/save' => "admin#save"
    delete '/destroy/:id' => "admin#destroy", as: 'destroy'
    get '/edit/:id' => "admin#edit", as:'edit'
    patch '/update/:id' => "admin#update", as: 'update'

  end

  root 'public#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :labels
	has_many :commands
	has_many :plangs
end

app/models/collection.rb
class Collection < ActiveRecord::Base
end

app/models/command.rb
class Command < ActiveRecord::Base
end

app/models/function.rb
class Function < ActiveRecord::Base
end

app/models/label.rb
class Label < ActiveRecord::Base
end

app/models/plang.rb
class Plang < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/weather.rb
class Weather < ActiveRecord::Base
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < Admin::BaseController
  # include Mercury::Authentication

  # layout :layout_with_mercury
  # helper_method :is_editing?

  def add
  	@article = Article.new
    @label = Label.uniq.pluck(:name)
    @plang = Plang.uniq.pluck(:name)
    @command = Command.uniq.pluck(:name)
    @body_class = 'add'
        
  end
  def save
  	@article = Article.new
  	@article.name = params[:article][:name]
  	@article.content = params[:article][:content]
  	@article.language = params[:article][:language]  
    if @article.save      
      property_save("labels",params[:label],false)    
      property_save("plangs",params[:plang],false)    
      property_save("commands",params[:command],false)    
      label_file_save
      redirect_to public_index_path
    else
      redirect_to :back
    end 	
  end
  def edit
    @article = Article.find(params[:id])    
    @article_label = @article.labels.pluck(:name)
    @article_plang = @article.plangs.pluck(:name)
    @article_command = @article.commands.pluck(:name)    
    @label = Label.uniq.pluck(:name) - @article_label
    @plang = Plang.uniq.pluck(:name) - @article_plang
    @command = Command.uniq.pluck(:name) - @article_command
    @body_class = 'add edit'
  end
  def destroy
    @article = Article.find(params[:id])
    @article.labels.destroy_all
    @article.plangs.destroy_all
    @article.commands.destroy_all
    @article.destroy
    label_file_save
    redirect_to '/'
  end

  def update
    @article = Article.find(params[:id])
    @article.update!(article_params)
    property_save("labels",params[:label],true)    
    property_save("plangs",params[:plang],true)    
    property_save("commands",params[:command],true)    
    label_file_save

    redirect_to '/'
  end
  private
  def property_save (property,param,update)    
    params = param.split(',')
    if update 
      existing_params = @article.send(property).all
      existing_params.each do |x|
        if !params.include?(x.name)
          params = params - [x.name] 
          x.destroy
        else
          params = params - [x.name] 
        end
      end
    end

    
    
    params.each do |x|
      s = @article.send(property).new
      s.name = x
      s.save      

    end
  end
  def label_file_save
    label = Collection.find_by_name('label')
    label.content = Label.uniq.pluck(:name).join(',')
    label.save
    plang = Collection.find_by_name('plang')
    plang.content = Plang.uniq.pluck(:name).join(',')
    plang.save
    command = Collection.find_by_name('command')
    command.content = Command.uniq.pluck(:name).join(',')
    command.save
     

  end

  def article_params
      params.require(:article).permit(:name, :content, :language)
  end


  
  # def layout_with_mercury
  #   !params[:mercury_frame] && is_editing? ? 'mercury' : 'application'
  # end

  # def is_editing?
  #   cookies[:editing] == 'true' && can_edit?
  # end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_filter :admin_filter

	def admin_filter
		if !user_signed_in?
			redirect_to index_path
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :label_load
  def label_load
  	@label_file = JSON.parse(IO.read("public/label.json"))
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  

  def public_filter
    if !user_signed_in?
      redirect_to public_index_path
    end
  end
  def search_tag_get
    @tags = []
    @tags.push(Collection.find_by_name('label').content.split(',')).push(Collection.find_by_name('plang').content.split(',')).push(Collection.find_by_name('command').content.split(','))
    render :json => @tags  
  end
  def index
  	@article = Article.all.order(:updated_at).reverse_order
  end
  def weather
    @weather = sun(params[:country],params[:city],params[:lat],params[:lng])
    
        render :json => @weather
    
  end
  def view
    @article = Article.find(params[:id])
    cookies[:last_viewed] = params[:id]
    respond_to do |format|      
  	   format.html {@article}
       format.json {render :json => @article}
    end

  end
  
  def yadg
    
  end
  
  def search
  	ids = []
    articles = []    
  	labels = params[:search_label].split(',')
  	plangs = params[:search_plang].split(',')
  	commands = params[:search_command].split(',')
  	labels.empty? ? nil : ids.concat(search_add(Label,labels))
  	plangs.empty? ? nil : ids.concat(search_add(Plang,plangs))
  	commands.empty? ? nil : ids.concat(search_add(Command,commands))
    ids.each do |x|

      if articles.empty?        
        articles.concat(x)
      else
        articles = articles & x
      end
    end    
    @article = Article.find(articles)
     respond_to do |format|      
       format.html {@article}
       format.json {render :json => @article}
    end
  end
  private
  def sun(country,city,lat,lng)
    require 'open-uri'
    if weather = Weather.where(city: city,country: country).first
      time = Time.now
      if weather.updated_at < time.midnight       
        astronomy_get(weather,lat,lng)
        condition_get(weather,lat,lng)
        weather.save
      elsif weather.updated_at + 5.hour < time
        condition_get(weather,lat,lng)
        weather.save
      end
    else
      weather = Weather.new
      weather.city = city 
      weather.country = country
      astronomy_get(weather,lat,lng)
      condition_get(weather,lat,lng)
      weather.save
    end
    return weather
  end
  def astronomy_get(weather,lat,lng)
    url = URI.encode("http://api.wunderground.com/api/28f50fb6f4b2ea5f/astronomy/q/#{lat},#{lng}.json")
    open(url) do |x|
      data = x.read
      json = JSON.parse(data)
      weather.riseh = json['moon_phase']['sunrise']['hour']
      weather.risem = json['moon_phase']['sunrise']['minute']
      weather.seth = json['moon_phase']['sunset']['hour']
      weather.setm = json['moon_phase']['sunset']['minute']
      weather.moonphase = json['moon_phase']['ageOfMoon']
    end 
  end
  def condition_get(weather,lat,lng)
    url = URI.encode("http://api.wunderground.com/api/28f50fb6f4b2ea5f/conditions/q/#{lat},#{lng}.json")
    open(url) do |x|
      data = x.read
      json = JSON.parse(data)
      weather.condition =  json['current_observation']['weather']
      weather.temp =  json['current_observation']['temp_c']
      weather.wind =  json['current_observation']['wind_kph']
    end
  end
  def search_add(label_type,param)
    local_ids = []
    param.each do |x|
      local_ids.push(label_type.where(name: x).pluck(:article_id))
    end
    return local_ids   

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def irj
		return "xyxy"
	end
	def svarci
		Article.delete_all
		Label.delete_all
		Plang.delete_all
		Command.delete_all
	end
	
end

app/views/admin/admin/add.html.erb
<%= javascript_tag do %>
	var labels = <%= raw @label.to_json %>
	var plangs = <%= raw @plang.to_json %>
	var commands = <%= raw @command.to_json  %>	
	var active_labels = [];
	var active_plangs = [];
	var active_commands = [];

<%end %>
<%= content_tag :div, class: "temp_information", data: {temp: @temp} do %>
<% end %>
<h1>Cikk hozzáadása</h1>
<hr>
<%= form_for @article, url:{action:"save"} do |f| %>
	
	<%= f.text_field :name , :placeholder => "Cím"%>
<br>
	<%= f.label :content,:id => 'primary' 'Szöveg' %> <br>
	<%= f.text_area :content,  :class => "tinymce", :rows => 15, :cols => 120 %>
<%= tinymce %>
<br>
<div class="row">
		
		<div class="col-lg-4">
			<div class="tag-container col-lg-12" data-target="label">			
				<h4>Cimkék</h4>
				<div class="inactive-tags">
					
				</div>
				<div class="active-tags">
					
				</div>							
				<input type="button" value="Új cimke" class="new-tag">
				<input type="text" class="add-tag">
			</div>				    
		    <%= text_field_tag :label,'', :class => "hidden" %>
	    </div>
		<div class="col-lg-4">
			<h4>Program nyelv</h4>
			<div class="tag-container col-lg-12" data-target="plang">			
				<div class="inactive-tags">
					
				</div>					
				<div class="active-tags">
												
				</div>				
				<input type="button" value="Új cimke" class="new-tag">		
				<input type="text" class="add-tag">
			</div>		
				    
		    <%= text_field_tag :plang,'', :class => "hidden" %>    
		</div>
		
		<div class="col-lg-4">
			<h4>Parancsok</h4>
			<div class="tag-container col-lg-12" data-target="command">
				<div class="inactive-tags">
					
				</div>
				<div class="active-tags">
							
				</div>						
				<input type="button" value="Új cimke" class="new-tag">
				<input type="text" class="add-tag">
			</div>				    
		    <%= text_field_tag :command,'', :class => "hidden" %>
		</div>
		
		
			
</div>	
<br> 
	
	<%= f.label :language, 'Nyelv' %>
	<%= f.select :language,([['Hungarian', 1], ['English', 2]]) %>

	<%= f.submit 'Mehet!' %>
<%end %>

app/views/admin/admin/destroy.html.erb
<h1>Admin#delete</h1>
<p>Find me in app/views/admin/delete.html.erb</p>

app/views/admin/admin/edit.html.erb
<%= javascript_tag do %>
	var labels = <%= raw @label.to_json %>
	var plangs = <%= raw @plang.to_json %>
	var commands = <%= raw @command.to_json  %>
	var active_labels = <%= raw @article_label.to_json %>
	var active_plangs = <%= raw @article_plang.to_json %>
	var active_commands = <%= raw @article_command.to_json %>

<%end %>

<h1>Cikk hozzáadása</h1>
<%= form_for @article, url:{action:"update"} do |f| %>
	<%= f.label :name, 'Cím' %>
	<%= f.text_field :name %>
<br>
	<%= f.label :content,:id => 'primary' 'Szöveg' %> <br>
	<%= f.text_area :content,  :class => "tinymce", :rows => 20, :cols => 120 %>
<%= tinymce %>
<br>
<div class="row">
		
		<div class="col-lg-4">
			<div class="tag-container col-lg-12" data-target="label">			
				<h4>Cimkék</h4>
				<div class="inactive-tags">
					
				</div>
				<div class="active-tags">
					
				</div>							
				<input type="button" value="Új cimke" class="new-tag">
				<input type="text" class="add-tag">
			</div>				    
		    <%= text_field_tag :label,'', :class => "hidden" %>
	    </div>
		<div class="col-lg-4">
			<h4>Program nyelv</h4>
			<div class="tag-container col-lg-12" data-target="plang">			
				<div class="inactive-tags">
					
				</div>					
				<div class="active-tags">
												
				</div>				
				<input type="button" value="Új cimke" class="new-tag">		
				<input type="text" class="add-tag">
			</div>		
				    
		    <%= text_field_tag :plang,'', :class => "hidden" %>    
		</div>
		
		<div class="col-lg-4">
			<h4>Parancsok</h4>
			<div class="tag-container col-lg-12" data-target="command">
				<div class="inactive-tags">
					
				</div>
				<div class="active-tags">
							
				</div>						
				<input type="button" value="Új cimke" class="new-tag">
				<input type="text" class="add-tag">
			</div>				    
		    <%= text_field_tag :command,'', :class => "hidden" %>
		</div>
		
		
			
</div>	
<br> 
	<%= f.label :language, 'Nyelv' %>
	<%= f.select :language,([['Hungarian', 1], ['English', 2]]) %>

	<%= f.submit 'Mehet!' %>
<%end %>

app/views/admin/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/layouts/admin.html.erb
<html>
<head>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= stylesheet_link_tag params[:controller] %>
	<%= javascript_include_tag params[:controller] %>
  


</head>



<body>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideclarevar</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
</head>
<body class="<%= @body_class %>">
<%= javascript_tag do %>
	var search_labels
	var search_plangs
	var search_commands	
	var active_search_labels = []
	var active_search_plangs = []
	var active_search_commands = []
	var article;
	var city, country;
	
  	$.getJSON( "/public/search_tag_get" )
	  	.done(function( json ) {
		    console.log(  json );
		    search_labels = json[0];
		    search_plangs = json[1];
    		search_commands = json[2];
			}
	)
  	
  	
	
	$( window).load(function() {
  				
			});


<%end %>	
    
	<div class="container-fluid space" style="padding:0;position:relative;overflow:hidden;">
		<div class="moon"></div>
		<div class="sun"></div>
		<!-- <div class="space"></div>	 -->
		<div class="top-section">
			<%random_cloud = rand(4)+1%> 
			<%=image_tag("cloud/dark-cloud-#{random_cloud}.png", :class => "cloud")%> 
			<!-- TITLE -->
			<div class="row">
				<div class="col-lg-12" style="text-align:center;">
					<h1 style="z-index:5;position:inherit"><%=link_to "/" do %>I DECLARE <i>var</i><%end %></h1>
				</div>
			</div>	
			<!-- MENÜ -->
			<div class="row menu" style="z-index:5;position:inherit">	
				<div class="col-lg-12 centered" style="float:none;text-align:center;">
					<ul class="nav nav-pills nav-justified">				
						<% if user_signed_in? %>
							<li><%= link_to 'Kilépés', destroy_user_session_path, method: :delete %></li>
							<li><%= link_to 'Cikk hozzáadása', admin_add_path %></li>
						<%else %>
							<li><%= link_to 'Belépés', new_user_session_path%></li>
							<li><%= link_to 'Regisztráció', new_user_registration_path%></li>
						<%end %>
						<li class="search"> <a href="" onclick="$('div.search').slideToggle();return false">Keresés</a>  </li>
					</ul>
				</div>
			</div>	
			<!-- KERESÉS -->	
			<div class="search" style="text-align:center;z-index:5;position:inherit">
				<!-- KERESŐ MEZŐK -->
				<div class="row">
					
					
					<div class="col-lg-4">
						<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#search-modal" onclick="search_refresh('search_labels')">
						  Cimkék
						</button>
		
						<%= text_field_tag(:search_label,'',:class => "hidden",:id => "search_labels") %>
					</div>
					<div class="col-lg-4">
						<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#search-modal" onclick="search_refresh('search_plangs')">
						  Program Nyelv
						</button>
						<%= text_field_tag(:search_plang,'',:class => "hidden",:id => "search_plangs") %>
					</div>
					<div class="col-lg-4">
						<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#search-modal" onclick="search_refresh('search_commands')">
						  Parancsok
						</button>
						<%= text_field_tag(:search_command,'',:class => "hidden",:id => "search_commands") %>
					</div>
					
				</div>		
				<br>
				<!-- KÜLDÉS GOMB -->
				<div class="row">
					<div class="col-lg-12" style="text-align:center">
						<%= submit_tag("Keresés", :class => "slide", :onclick => "ajax_search()") %>
						
					</div>				
				</div>
			</div>
			</div>
			<%=image_tag("land/city-1.png", :class => "silhouette")%> 
	</div>
	<!-- FEJLÉC VÉGE -->
	<div class="container-fluid" style="background-color:black;z-index:5;min-height:50vh;position:relative;">

		<%=session[:last_viewed] %>
		<h1 class="city-welcome" style="text-align:center;color:teal;"></h1>
		<%= yield %>
	</div>
	<div class="modal fade" id="search-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  		<div class="modal-dialog">
  		  <div class="modal-content">
  		    <div class="modal-header">
  		      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  		      <h4 class="modal-title" id="myModalLabel">Modal title</h4>
  		    </div>
  		    <div class="modal-body">
  		      <div id="inactive-search">
  		      	
  		      </div>
  		      <div id="active-search">
  		      	
  		      </div>
  		    </div>
  		    <div class="modal-footer">
  		      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>  		      
  		    </div>
  		  </div>
  		</div>
	</div>
</body>
</html>